### ISSUE TITLE
Any body came across this error?

### ISSUE THREAD

**Issue by xiaozhi2015** [Sxjdwang/TalkLip#14]
@Sxjdwang 
python3 inf_demo.py --video_path ./data/jtest.mp4 --wav_path ./data/jtest.wav --ckpt_path ./global_contrastive.pth --avhubert_root ./av_hubert/
Traceback (most recent call last):
  File "inf_demo.py", line 280, in <module>
    synt_demo(fa, device, model, args)
  File "inf_demo.py", line 234, in synt_demo
    prediction, _ = model(sample, inps, idAudio, spectrogram.shape[0])
  File "/home/paddle/python3.7/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/ai/lzhh/digital_human/TalkLip/models/talklip.py", line 103, in forward
    enc_out = self.audio_encoder(**sample["net_input"])
  File "/home/paddle/python3.7/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "./av_hubert/avhubert/hubert_asr.py", line 386, in forward
    x, padding_mask = self.w2v_model.extract_finetune(**w2v_args)
  File "./av_hubert/avhubert/hubert.py", line 704, in extract_finetune
    features_audio = self.forward_features(src_audio, modality='audio') # features: [B, F, T]
  File "./av_hubert/avhubert/hubert.py", line 541, in forward_features
    features = extractor(source)
  File "/home/paddle/python3.7/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "./av_hubert/avhubert/hubert.py", line 327, in forward
    x = self.proj(x.transpose(1, 2))
  File "/home/paddle/python3.7/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/paddle/python3.7/lib/python3.7/site-packages/torch/nn/modules/linear.py", line 114, in forward
    return F.linear(input, self.weight, self.bias)
RuntimeError: mat1 and mat2 shapes cannot be multiplied (250x160 and 104x768)

**Comment by xiaozhi2015** [comment]
change torch to  1.10.1 and torchvision to 0.11.2, solved this problem.
