### ISSUE TITLE
[Bug] TypeError: 'NoneType' object is not subscriptable in "utils /data_avhubert.py"

### ISSUE THREAD

**Issue by LZY-WHU** [Sxjdwang/TalkLip#35]
Hi! I encountered the following error when using the demo for inference: 
```python
Traceback (most recent call last):
  File "inf_demo.py", line 284, in <module>
    synt_demo(fa, device, model, args)
  File "inf_demo.py", line 248, in synt_demo
    for j, im in enumerate(processed_img[0]):
TypeError: 'NoneType' object is not subscriptable
```
I checked that `processd_img` comes from the `emb_roi2im` function in `utils/data_avhubert.py`, which I suspect it is missing the return value.
```python
def emb_roi2im(pickedimg, imgs, bbxs, pre, device):
    trackid = 0
    height, width, _ = imgs[0][0].shape
    for i in range(len(pickedimg)):
        idimg = pickedimg[i]
        imgs[i] = imgs[i].float().to(device)
        for j in range(len(idimg)):
            bbx = bbxs[i][idimg[j]]
            if bbx[2] > width: bbx[2] = width
            if bbx[3] > height: bbx[3] = height
            resize2ori = transforms.Resize([bbx[3] - bbx[1], bbx[2] - bbx[0]])
            try:
                resized = resize2ori(pre[trackid + j] * 255.).permute(1, 2, 0)
                imgs[i][idimg[j]][bbx[1]:bbx[3], bbx[0]:bbx[2], :] = resized
            except:
                print(bbx, resized.shape)
                import sys
                sys.exit()
        trackid += len(idimg)
```
Based on my intuition, I added the `return imgs` after it and the reasoning code ran normally.

**Comment by Sxjdwang** [comment]
Thank you for pointing out this bug. I checked the history of this file. You are correct about adding "return imgs".

**Comment by LZY-WHU** [comment]
收到，辛苦啦！
