### ISSUE TITLE
Could you please provide some example input audio and video ?

### ISSUE THREAD

**Issue by EmmaThompson123** [Sxjdwang/TalkLip#50]
I run `python inf_demo.py --video_path input.mp4 --wav_path input.wav --ckpt_path ./checkpoint/global_contrastive.pth --avhubert_root /repo/av_hubert`,but I can not get good result, so could you please provide some example input audio and video ? and the audio better in Chinese

**Comment by xiaoliu123881** [comment]
hello，Did you encounter this problem while running it python inf_demo.py --video_path input.mp4 --wav_path input.wav --ckpt_path ./checkpoint/global_contrastive.pth --avhubert_root /repo/av_hubert？


TalkLip-main$ python inf_demo.py --video_path /public/datasets/lsy/asserts/examples/test12.mp4 --wav_path /public/datasets/lsy/asserts/examples/driving_audio_2.wav --ckpt_path /public/datasets/lsy/global_only.pth --avhubert_root /home/liusuying/TalkLip-main/av_hubert

Traceback (most recent call last):
  File "inf_demo.py", line 160, in <module>
    model = TalkLip(*build_encoder(args.avhubert_root)).to(device)
  File "inf_demo.py", line 51, in build_encoder
    encoder_ = task_pretrain.build_model(w2v_args.model)
  File "/home/liusuying/.conda/envs/talk/lib/python3.8/site-packages/fairseq/tasks/fairseq_task.py", line 324, in build_model
    model = models.build_model(cfg, self)
  File "/home/liusuying/.conda/envs/talk/lib/python3.8/site-packages/fairseq/models/__init__.py", line 96, in build_model
    return model.build_model(cfg, task)
  File "/home/liusuying/TalkLip-main/av_hubert/avhubert/hubert.py", line 439, in build_model
    model = AVHubertModel(cfg, task.cfg, task.dictionaries, **kwargs)
  File "/home/liusuying/TalkLip-main/av_hubert/avhubert/hubert_pretraining.py", line 194, in dictionaries
    return self.state.dictionaries
  File "/home/liusuying/.conda/envs/talk/lib/python3.8/site-packages/fairseq/tasks/fairseq_task.py", line 41, in __getattr__
    self._state[name] = self._factories[name]()
  File "/home/liusuying/TalkLip-main/av_hubert/avhubert/hubert_pretraining.py", line 198, in load_dictionaries
    dictionaries = [
  File "/home/liusuying/TalkLip-main/av_hubert/avhubert/hubert_pretraining.py", line 199, in <listcomp>
    Dictionary.load(f"{label_dir}/dict.{label}.txt")
  File "/home/liusuying/.conda/envs/talk/lib/python3.8/site-packages/fairseq/data/dictionary.py", line 216, in load
    d.add_from_file(f)
  File "/home/liusuying/.conda/envs/talk/lib/python3.8/site-packages/fairseq/data/dictionary.py", line 229, in add_from_file
    raise fnfe
  File "/home/liusuying/.conda/envs/talk/lib/python3.8/site-packages/fairseq/data/dictionary.py", line 226, in add_from_file

**Comment by xiaoliu123881** [comment]
> I run `python inf_demo.py --video_path input.mp4 --wav_path input.wav --ckpt_path ./checkpoint/global_contrastive.pth --avhubert_root /repo/av_hubert`,but I can not get good result, so could you please provide some example input audio and video ? and the audio better in Chinese我运行 `python inf_demo.py --video_path input.mp4 --wav_path input.wav --ckpt_path ./checkpoint/global_contrastive.pth --avhubert_root /repo/av_hubert` ，但无法获得良好的结果，因此您能否提供一些示例输入音频和视频？中文音频效果更好

hello，Did you encounter this problem while running it python inf_demo.py --video_path input.mp4 --wav_path input.wav --ckpt_path ./checkpoint/global_contrastive.pth --avhubert_root /repo/av_hubert？


TalkLip-main$ python inf_demo.py --video_path /public/datasets/lsy/asserts/examples/test12.mp4 --wav_path /public/datasets/lsy/asserts/examples/driving_audio_2.wav --ckpt_path /public/datasets/lsy/global_only.pth --avhubert_root /home/liusuying/TalkLip-main/av_hubert

Traceback (most recent call last):
  File "inf_demo.py", line 160, in <module>
    model = TalkLip(*build_encoder(args.avhubert_root)).to(device)
  File "inf_demo.py", line 51, in build_encoder
    encoder_ = task_pretrain.build_model(w2v_args.model)
  File "/home/liusuying/.conda/envs/talk/lib/python3.8/site-packages/fairseq/tasks/fairseq_task.py", line 324, in build_model
    model = models.build_model(cfg, self)
  File "/home/liusuying/.conda/envs/talk/lib/python3.8/site-packages/fairseq/models/__init__.py", line 96, in build_model
    return model.build_model(cfg, task)
  File "/home/liusuying/TalkLip-main/av_hubert/avhubert/hubert.py", line 439, in build_model
    model = AVHubertModel(cfg, task.cfg, task.dictionaries, **kwargs)
  File "/home/liusuying/TalkLip-main/av_hubert/avhubert/hubert_pretraining.py", line 194, in dictionaries
    return self.state.dictionaries
  File "/home/liusuying/.conda/envs/talk/lib/python3.8/site-packages/fairseq/tasks/fairseq_task.py", line 41, in __getattr__
    self._state[name] = self._factories[name]()
  File "/home/liusuying/TalkLip-main/av_hubert/avhubert/hubert_pretraining.py", line 198, in load_dictionaries
    dictionaries = [
  File "/home/liusuying/TalkLip-main/av_hubert/avhubert/hubert_pretraining.py", line 199, in <listcomp>
    Dictionary.load(f"{label_dir}/dict.{label}.txt")
  File "/home/liusuying/.conda/envs/talk/lib/python3.8/site-packages/fairseq/data/dictionary.py", line 216, in load
    d.add_from_file(f)
  File "/home/liusuying/.conda/envs/talk/lib/python3.8/site-packages/fairseq/data/dictionary.py", line 229, in add_from_file
    raise fnfe
  File "/home/liusuying/.conda/envs/talk/lib/python3.8/site-packages/fairseq/data/dictionary.py", line 226, in add_from_file

**Comment by guo-king666** [comment]
请问一下这个python inf_demo.py命令你运行成功了吗，步骤是什么呢
